exclude: [vendor, tag-generator.py]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://notoootori.github.io"
plugins:
  - jekyll-sitemap
