exclude: [vendor, tools]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
kramdown:
  input: GFM
  # Disable kramdown hightlighter and use highlight.js instead
  syntax_highlighter: nil

url: "https://notoootori.github.io"

plugins:
  - jekyll-sitemap
