name: build-site
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: update-tags
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: generate-tags
        run: python3 tools/tag-generator.py

      - name: push-tag-update
        uses: EndBug/add-and-commit@v7
        with:
          add: 'tags/*.md'
          default_author: github_actions
          message: 'chore(tags): generate tags automatically'
          push: true

  build:
    name: build-site
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: cache-website
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: push-site-build
        uses: NotoOotori/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
