name: Build Website
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Generate Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Update Tags
        run: python3 tools/tag-generator.py

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'tags/*.md'
          default_author: github_actions
          message: 'chore(tags): generate tags automatically'
          push: true

  build:
    name: Build Website and Push
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Website
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build Website and Push
        uses: NotoOotori/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
