name: Prebuild Site for Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Prebuild site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Update tags
        run: python3 tools/tag-generator.py

      - name: Push tag update
        uses: EndBug/add-and-commit@v7
        with:
          add: 'tags/*.md'
          default_author: github_actions
          message: 'chore(tags): update tags automatically'
          push: true

      - name: Cache website
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Prebuild site and push to gh-pages
        uses: NotoOotori/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
