name: Test Site
on:
  schedule:
    - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  test:
    name: Test site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.6.3
          # Run 'bundle install' and cache installed gems automatically
          bundler-cache: true

      - name: Install html-proofer
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: gem install html-proofer

      - name: Cache html-proofer
        # Switch to official version only if
        # https://github.com/actions/cache/issues/92
        # is resolved
        uses: pat-s/always-upload-cache@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer

      - name: Run html-proofer
        run: htmlproofer ./
